"""vehicle

Revision ID: 2613598563cb
Revises: c04bf689b0b3
Create Date: 2022-01-06 19:00:27.036470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2613598563cb'
down_revision = 'c04bf689b0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detrack_id', sa.String(), nullable=False),
    sa.Column('vehicle_name_no', sa.String(), nullable=False),
    sa.Column('speed_limit', sa.Integer(), nullable=True),
    sa.Column('stationary_limit', sa.Integer(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=True),
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('zones', sa.String(), nullable=True),
    sa.Column('vehicle_types', sa.String(), nullable=True),
    sa.Column('created_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
