"""job+1

Revision ID: 9dae30fcfdfc
Revises: a4cf70992f85
Create Date: 2022-01-11 13:57:40.084936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9dae30fcfdfc'
down_revision = 'a4cf70992f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('job', 'type',
               existing_type=postgresql.ENUM('delivery', 'collection', name='job_type_enum'),
               nullable=False)
    op.alter_column('job', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job', 'do',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobitem', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobitem', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobitem', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobitem', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobitem', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobitem', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job', 'do',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job', 'type',
               existing_type=postgresql.ENUM('delivery', 'collection', name='job_type_enum'),
               nullable=True)
    op.alter_column('job', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
