"""job

Revision ID: a4cf70992f85
Revises: 2613598563cb
Create Date: 2022-01-10 12:48:32.240509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4cf70992f85'
down_revision = '2613598563cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.Enum('delivery', 'collection', name='job_type_enum'), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('deliver_to_collect_from', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('assign_to', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('received_by_sent_by', sa.String(), nullable=True),
    sa.Column('do', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('pod_lat', sa.Float(), nullable=True),
    sa.Column('pod_lng', sa.Float(), nullable=True),
    sa.Column('job_price', sa.String(), nullable=True),
    sa.Column('total_price', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('address_lat', sa.Float(), nullable=True),
    sa.Column('address_lng', sa.Float(), nullable=True),
    sa.Column('created_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobitem',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('reject', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['updated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobitem')
    op.drop_table('job')
    # ### end Alembic commands ###
