"""detrack_id

Revision ID: c04bf689b0b3
Revises: 714b1b59e1e5
Create Date: 2022-01-06 12:34:30.715323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c04bf689b0b3'
down_revision = '714b1b59e1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detrackid',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('detrack_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detrackid')
    # ### end Alembic commands ###
