"""job+4

Revision ID: c21e22bb42d8
Revises: 4b4b26f8d958
Create Date: 2022-01-11 18:18:55.472114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21e22bb42d8'
down_revision = '4b4b26f8d958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobitem_job_id_fkey', 'jobitem', type_='foreignkey')
    op.create_foreign_key(None, 'jobitem', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobitem', type_='foreignkey')
    op.create_foreign_key('jobitem_job_id_fkey', 'jobitem', 'job', ['job_id'], ['id'])
    # ### end Alembic commands ###
