"""job+2

Revision ID: dfa01745aa21
Revises: 9dae30fcfdfc
Create Date: 2022-01-11 18:02:34.068293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa01745aa21'
down_revision = '9dae30fcfdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'status')
    op.drop_column('job', 'priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
